string_utilities: string_utilities.c main.c string_utilities.h
	gcc -o string_utilities string_utilities.c main.c

trim: string_utilities.c main2.c string_utilities.h
	gcc -o trim string_utilities.c main2.c