#!/bin/bash

if [[ $# != 0 ]]
then
    echo "Error" >&2
    exit 1
fi

while read line
do
    for item in $line
    do
	if [[ $item =~ ^[a-zA-Z0-9]+$ ]]
	then
            echo "$item"
	fi
    done
done
