#!/bin/bash

if [[ $1 && $2 =~ ^(\-|\+)?[0-9]{0,9}$ ]]
then
    
    if [[ $1 -lt $2 ]]
    then
        echo "$1"
        exit 0
    elif [[ $1 -gt $2 ]]
    then
        echo "$2"
        exit 0
    else
        echo "Erorr" >&2
        exit 1
    fi
fi

